In [ ]:
import pandas as pd
print("Python & Pandas are Working")

Python & Pandas are Working

In [ ]:
data = {
    "Vehicle Model": ["A1","B1","C1"],
    "UnitSold": [12, 10, 8],
    "Revenue": [360000,300000, 240000],
}

In [ ]:
data

{'Vehicle Model': ['A1', 'B1', 'C1'],
 'UnitSold': [12, 10, 8],
 'Revenue': [360000, 300000, 240000]}

In [ ]:
df = pd.DataFrame(data)

In [ ]:
df

  Vehicle Model  UnitSold  Revenue
0            A1        12   360000
1            B1        10   300000
2            C1         8   240000

In [ ]:
df.shape

(3, 3)

In [ ]:
df.columns

Index(['Vehicle Model', 'UnitSold', 'Revenue'], dtype='object')

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Vehicle Model  3 non-null      object
 1   UnitSold       3 non-null      int64
 2   Revenue        3 non-null      int64
dtypes: int64(2), object(1)
memory usage: 204.0+ bytes

In [ ]:
df.describe()

       UnitSold   Revenue
count       3.0       3.0
mean       10.0  300000.0
std         2.0   60000.0
min         8.0  240000.0
25%         9.0  270000.0
50%        10.0  300000.0
75%        11.0  330000.0
max        12.0  360000.0

In [ ]:
df["Revenue"]

0    360000
1    300000
2    240000
Name: Revenue, dtype: int64

In [ ]:
df["Revenue"].sum()

np.int64(900000)

In [ ]:
df["UnitSold"].sum()

np.int64(30)

In [ ]:
df["Revenue"].mean()

np.float64(300000.0)

In [ ]:
df["Revenue"].max()

360000

In [ ]:
df["Revenue"].idxmax()

0

In [ ]:
df.loc[0, "Vehicle Model"]

'A1'

In [ ]:
df.sort_values("Revenue", ascending=False)

  Vehicle Model  UnitSold  Revenue  Revenue Per Unit
0            A1        12   360000           30000.0
1            B1        10   300000           30000.0
2            C1         8   240000           30000.0

In [ ]:
df["Revenue"] > 300000

0     True
1    False
2    False
Name: Revenue, dtype: bool

In [ ]:
df[df["Revenue"] > 300000]

  Vehicle Model  UnitSold  Revenue  Revenue Per Unit
0            A1        12   360000           30000.0

In [ ]:
df["Revenue Per Unit"] = df["Revenue"] / df["UnitSold"]

In [ ]:
df

  Vehicle Model  UnitSold  Revenue  Revenue Per Unit
0            A1        12   360000           30000.0
1            B1        10   300000           30000.0
2            C1         8   240000           30000.0

In [ ]:
df[["Vehicle Model", "Revenue Per Unit"]]

  Vehicle Model  Revenue Per Unit
0            A1           30000.0
1            B1           30000.0
2            C1           30000.0

All three vehicle models generate the same revenue per unit at 30000. Therefore the difference in total revenue is caused by unit sold not by the revenue earned per unit.

In [ ]:
df.groupby("Vehicle Model")["Revenue"].sum()

Vehicle Model
A1    360000
B1    300000
C1    240000
Name: Revenue, dtype: int64

# New Section